/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import negocio.produccion;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import util.Funciones;
import util.Reportes;

/**
 *
 * @author USER
 */
public class frmReporteProduccion extends javax.swing.JDialog {

    /**
     * Creates new form reporteProduccion
     */
    public frmReporteProduccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setTitle("Reporte Por Fecha De Producción");
        this.setLocationRelativeTo(null);
        cargarFecha();
        txtHasta.setEnabled(false);
        txtDesde.setEnabled(false);
    }

    private void cargarFecha() {
        java.util.Date fecha = new java.util.Date();
        txtHasta.setDate(fecha);
        txtDesde.setDate(fecha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbHoy = new javax.swing.JRadioButton();
        rbFecha = new javax.swing.JRadioButton();
        rbTodasFechas = new javax.swing.JRadioButton();
        txtDesde = new com.toedter.calendar.JDateChooser();
        txtHasta = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(rbHoy);
        rbHoy.setSelected(true);
        rbHoy.setText("Hoy");

        buttonGroup1.add(rbFecha);
        rbFecha.setText("Por Fecha");
        rbFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rbFechaFocusLost(evt);
            }
        });
        rbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTodasFechas);
        rbTodasFechas.setText("Todas las Fechas");

        jLabel2.setText("Desde:");

        jLabel3.setText("Hasta: ");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTodasFechas)
                    .addComponent(rbHoy)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rbFecha)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rbHoy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFecha)
                    .addComponent(jLabel2)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addComponent(rbTodasFechas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbFechaFocusGained

        txtHasta.setEnabled(true);
        txtDesde.setEnabled(true);
    }//GEN-LAST:event_rbFechaFocusGained

    private void rbFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbFechaFocusLost

        txtHasta.setEnabled(false);
        txtDesde.setEnabled(false);
    }//GEN-LAST:event_rbFechaFocusLost

    private void rbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaActionPerformed

    }//GEN-LAST:event_rbFechaActionPerformed

    public String nombreArchivoReporte="";
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        try {
            int tipo = 0;

            if (rbHoy.isSelected()) {
                tipo = 1;
            } else if (rbFecha.isSelected()) {
                tipo = 2;
            } else if (rbTodasFechas.isSelected()) {
                tipo = 3;
            }

            java.sql.Date fecha1 = new java.sql.Date(txtDesde.getDate().getTime());
            java.sql.Date fecha2 = new java.sql.Date(txtHasta.getDate().getTime());
            
            nombreArchivoReporte="reporteProduccion.jasper";
            dispose();
//            new Reportes().reporteProduccion(nombreArchivoReporte, fecha1, fecha2, tipo);
            new Reportes().reporte3Parametros(nombreArchivoReporte, fecha1, "fecha_inicio", fecha2, "fecha_final", tipo, "tipo").setVisible(true);
            
        } catch (Exception e) {
            Funciones.mensajeError(e.getMessage(), "Error");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JRadioButton rbHoy;
    private javax.swing.JRadioButton rbTodasFechas;
    private com.toedter.calendar.JDateChooser txtDesde;
    private com.toedter.calendar.JDateChooser txtHasta;
    // End of variables declaration//GEN-END:variables
}
